export ChangePassword from './ChangePassword';
export EditProfile from './EditProfile';
export Header from './Header';
export Home from './Home';
export Orders from './Orders';
export Products from './Products';
export Withdraws from './Withdraws';
export Categories from './Categories';
export EditCategory from './EditCategory';
export Users from './Users';
export Currencies from './Currencies.js';
export Settings from './Settings.js'
